### ISSUE TITLE
Lucee 5.0.0.252 / Mura 6.2.6543 Error on Plugin Install

### ISSUE THREAD

**Issue by gpearson** [stevewithington/MuraFW1#41]
My development server is running Railo 4.5 and Production Server is Lucee 5.0.0.252. Upon trying to install a Plugin I am getting the following error message

`500 Error
Page /plugins/25/plugin/config.xml.cfm [/var/www/virtuals/www.yourcfpro.com/html/plugins/25/plugin/config.xml.cfm] not found 

Code: 0 

Type: missinginclude 

			
				lucee.runtime.exp.MissingIncludeException: Page /plugins/25/plugin/config.xml.cfm [/var/www/virtuals/www.yourcfpro.com/html/plugins/25/plugin/config.xml.cfm] not found
	at lucee.runtime.PageSourceImpl.loadPage(PageSourceImpl.java:894)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:888)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:808)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:803)
	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:794)
	at plugin.pluginmanager_cfc$cf.udfCall2(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc:861)
	at plugin.pluginmanager_cfc$cf.udfCall(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:770)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570)
	at plugin.pluginmanager_cfc$cf.udfCall1(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc:448)
	at plugin.pluginmanager_cfc$cf.udfCall(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)
	at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:779)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:793)
	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1580)
	at plugin.pluginmanager_cfc$cf.udfCall1(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc:368)
	at plugin.pluginmanager_cfc$cf.udfCall(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1902)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570)
	at admin.core.controllers.csettings_cfc$cf.udfCall1(/var/www/virtuals/www.yourcfpro.com/html/admin/core/controllers/csettings.cfc:128)
	at admin.core.controllers.csettings_cfc$cf.udfCall(/var/www/virtuals/www.yourcfpro.com/html/admin/core/controllers/csettings.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:210)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1915)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)
	at admin.framework_cfc$cf.udfCall6(/var/www/virtuals/www.yourcfpro.com/html/admin/framework.cfc:1308)
	at admin.framework_cfc$cf.udfCall(/var/www/virtuals/www.yourcfpro.com/html/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:770)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:752)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1570)
	at admin.framework_cfc$cf.udfCall2(/var/www/virtuals/www.yourcfpro.com/html/admin/framework.cfc:517)
	at admin.framework_cfc$cf.udfCall(/var/www/virtuals/www.yourcfpro.com/html/admin/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:105)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:337)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:224)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1902)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:422)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:224)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2250)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2242)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2210)
	at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:846)
	at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:103)
	at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:872)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

			

Column: 0
ID: ??
Line: 861
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall2(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc:861)
Template: /var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 448
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall1(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc:448)
Template: /var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 368
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall1(/var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc:368)
Template: /var/www/virtuals/www.yourcfpro.com/html/requirements/mura/plugin/pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 128
Raw Trace: admin.core.controllers.csettings_cfc$cf.udfCall1(/var/www/virtuals/www.yourcfpro.com/html/admin/core/controllers/csettings.cfc:128)
Template: /var/www/virtuals/www.yourcfpro.com/html/admin/core/controllers/csettings.cfc
Type: cfml

Column: 0
ID: ??
Line: 1308
Raw Trace: admin.framework_cfc$cf.udfCall6(/var/www/virtuals/www.yourcfpro.com/html/admin/framework.cfc:1308)
Template: /var/www/virtuals/www.yourcfpro.com/html/admin/framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 517
Raw Trace: admin.framework_cfc$cf.udfCall2(/var/www/virtuals/www.yourcfpro.com/html/admin/framework.cfc:517)
Template: /var/www/virtuals/www.yourcfpro.com/html/admin/framework.cfc
Type: cfml
`

Any ideas on where I can look to get the Plugin installed on Lucee

**Comment by gpearson** [comment]
Solved this as it was a directory that began with a . which was used to put notes about the plugin in to make sure it did everything on the roadmap.
